# Generated by Django 4.0.3 on 2022-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_certificados_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='expiration_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
