# Generated by Django 4.0.3 on 2022-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_certificados_expiration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='expiration_at',
            field=models.DateTimeField(null=True),
        ),
    ]
