# Generated by Django 4.0.3 on 2022-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_certificados_expiration_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='expiration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
