# Generated by Django 4.0.3 on 2022-04-05 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_certificados_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 5, 12, 32, 29, 803465)),
        ),
    ]
