# Generated by Django 4.0.3 on 2022-04-05 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_certificados_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 5, 14, 37, 56, 157964)),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='expiration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='expiration_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
