# Generated by Django 4.0.3 on 2022-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_certificados_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
