# Generated by Django 4.0.3 on 2022-04-05 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_certificados_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime.today),
        ),
    ]
