# Generated by Django 4.0.3 on 2022-04-05 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_certificados_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 15, 59, 23, 318971)),
        ),
    ]
