# Generated by Django 4.0.3 on 2022-04-05 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_certificados_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 16, 53, 52, 344575)),
        ),
    ]
